name: repository_ustp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Network
  http: ^1.2.2
  #State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  #Storage
  shared_preferences: ^2.2.3
  #Styling
  hexcolor: ^3.0.1
  loader_skeleton: ^0.0.4
  smooth_page_indicator: ^1.2.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
