name: repository_ustp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Essential
  intl: ^0.18.1
  
  # Network
  http: ^0.13.6
  
  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6

  # Firebase
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5

  # Storage
  shared_preferences: ^2.2.3

  # Media
  file_picker: ^8.0.5
  open_file: ^3.3.2
  url_launcher: ^6.0.9
  video_player: ^2.5.0
  pdf_render: ^1.4.12
  webview_flutter: ^4.8.0
  syncfusion_flutter_pdfviewer: ^20.4.42
  syncfusion_flutter_core: ^20.4.42

  # Documents
  printing: ^5.5.0
  pdf: ^3.6.0

  # Styling
  hexcolor: ^3.0.1
  loader_skeleton: ^0.0.4
  smooth_page_indicator: ^1.2.0+3

  # Widgets
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
